name: amdb-bioinfo-course

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.12
  - pip

  # Jupyter y soporte de notebooks
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets

  # Librerias de Python usadas en las notebooks
  - numpy
  - pandas
  - matplotlib
  - biopython
  - requests
  - scipy
  - scikit-learn

  # Utilidades bioinfo y linea de comandos
  - bwa
  - samtools
  - tree
  - gawk
  - sed
  - grep
  - coreutils
  - findutils
  - tar
  - gzip
  - vim
  - nano
  - git

  # Otros 
  - ripgrep

  # Paquetes pip
  - pip:
      - bash_kernel
